package uk.ac.standrews.cs.trombone.event.environment;

import uk.ac.standrews.cs.trombone.core.util.Copyable;

/**
 * Generates intervals in nanoseconds.
 *
 * @author Masih Hajiarabderkani (mh638@st-andrews.ac.uk)
 */
public interface IntervalGenerator extends Copyable {

    /**
     * Gets the next interval at the given time.
     *
     * @param time_nanos the time in nanoseconds at which to generate an interval
     * @return interval in nanoseconds
     */
    long get(long time_nanos);

    /**
     * Gets the mean interval in nanoseconds at the given time.
     *
     * @param time_nanos the time in nanoseconds at which to get the mean interval
     * @return the mean interval in nanoseconds for the intervals that are generated by this generator.
     */
    long getMeanAt(long time_nanos);

    @Override
    IntervalGenerator copy();
}